"""
Django settings for int01be project.

Generated by 'django-admin startproject' using Django 4.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import socket
hostname = socket.gethostname()

from corsheaders.defaults import default_headers
from pathlib import Path
import mongoengine

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a#-z+xnf6^yag#u7^z93zkp!8s%gly2jaep)lo%lwiae-r8^rn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


if "laptop" in hostname.lower():
    # Local development
    ALLOWED_HOSTS = ["127.0.0.1", "localhost", "testserver"]
else:
    # Remote server
    ALLOWED_HOSTS = ["enlightenlab.com", "www.enlightenlab.com", "172.105.120.124"]


ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'testserver', # 'testserver' is the default hostname used by Django's built-in testing tools, specifically the django.test.Client.
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'django_extensions',
]

INSTALLED_APPS_1 = [
    #'simple1',
    #'simple4',
    "tokentask",
    #"simple6",
    #"simple7",
    "core",
    "plugins",
    "home",
]

INSTALLED_APPS += INSTALLED_APPS_1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'int01be.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True, # the templates in the installed apps are visible
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

TEMPLATES_0_DIR_1 = [
    BASE_DIR / "plugins/home/templates",
    BASE_DIR / "plugins/app1/templates",
    BASE_DIR / "plugins/app2/templates",
    BASE_DIR / "plugins/app3/templates",
    BASE_DIR / "plugins/mcqset1/templates",
    BASE_DIR / "plugins/mcqset2/templates",
]

TEMPLATES[0]['DIRS'] += TEMPLATES_0_DIR_1

WSGI_APPLICATION = 'int01be.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

#STATIC_URL = 'static/'
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#
# Custom
#

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:4200',
    "http://127.0.0.1:4200",
]

CORS_ALLOW_CREDENTIALS = True
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access CSRF token
CSRF_COOKIE_SECURE = False  # Set to True if using HTTPS
CSRF_COOKIE_SAMESITE = "Lax"  # Allow CSRF cookie to be sent

CORS_ALLOWED_ORIGINS = [
    "http://127.0.0.1:4200",
    "http://localhost:4200",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    'X-Request-Type',
    'X-Anonymous-Token',
    'x-refresh-token',
    #'Cache-Control',
    #'Pragma',
]

# MongoDB connection setup
mongoengine.connect(
    db='int01be_development',             # Name of the database
    #username='your_username',      # Optional, if authentication is required
    #password='your_password',      # Optional, if authentication is required
    host='localhost',              # MongoDB server address
    port=27017                     # MongoDB default port (optional)
)

MONGO_DB_NAME = "int01be_development"
MONGO_URI = "mongodb://localhost:27017/"

REDIS_HOST = 'localhost'
REDIS_PORT = 6379

# Authentication system is project level in Django.
LOGIN_URL = "/core/login/"
LOGIN_REDIRECT_URL = "/core/home/"
LOGOUT_REDIRECT_URL = "/core/login/"