from .models_mongo import UserGameState, Page1State, Page2State


def get_user_key(request):
    """
    Use Django user if logged in; else use session key.
    
    Since authentication is not set up:
    - request.user == AnonymousUser()
    - request.user.is_authenticated == False
    """

    # Print for debugging
    #print(request.user.is_authenticated, request.session.session_key)

    if request.user.is_authenticated:
        return str(request.user.id)

    # Ensure session exists and get session key - 
    # this is not the same as token! token is user-entered, session key is sytem generated
    # session key is randomly generated by server,
    # stored (as value) on browser as cookie, usually as sessionid (the key)
    if not request.session.session_key:
        request.session.save()  # creates the session and cookie
    return request.session.session_key  # now guaranteed to be non-None


def get_or_create_game_state(request):
    """
    Returns a MongoEngine document for this user/session,
    creating one if it doesn't exist.
    """
    user_key = get_user_key(request)

    doc = UserGameState.objects(user_id=user_key).first()
    if doc is None:
        doc = UserGameState(user_id=user_key)
        doc.save()
    return doc


def get_page1_state(request):
    """
    Returns a MongoEngine document for this user/session,
    creating one if it doesn't exist.
    """
    doc = Page1State.objects().first()
    if doc is None:
        doc = Page1State()
        doc.save()
    return doc


def get_page2_state(request):
    """
    Returns a MongoEngine document for this user/session,
    creating one if it doesn't exist.
    """
    doc = Page2State.objects().first()
    if doc is None:
        doc = Page2State()
        doc.save()
    return doc
